### ISSUE TITLE
Allow to configure smartling directives via command line

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#34]
**Use case**:
I need to upload a file with a specific custom placeholder.

**Solution**:
It can be done by including smartling directives into upload request. We already have support directives through config file. But it would be nice to allow user configure directives in a command line. Especially for ‘testing’ and ‘trying’ configurations.

**DoD**:
* Add the new optional parameter `-r | --directive`
* Description TBD
* Add example of usage into `examples.md`
```
smartling-cli files push *.xml -r namespace="namespace for my file" -r placeholder_format_custom="@@.*?@@"
```

**Comment by seletskiy** [comment]
@dimitrystd: Please, check it out.

**Comment by dimitrystd** [comment]
Tested it today. For some reason, it doesn't work at all.
```
$ smartling-cli files push dir11/test.xml --directive smartling.string_format_paths="html : translationObjectFile/translationObjectProperties/"
dir11/test.xml (xml) overwritten [1 strings 27 words]
```
In order to check actual directives you should get file status
```
GET https://api.smartling.com/files-api/v2/projects/e009ee2d5/file/status?fileUri=dir11%2Ftest.xml

{
    "response": {
        "code": "SUCCESS",
        "data": {
            "fileUri": "dir11/test.xml",
            "lastUploaded": "2017-09-27T22:34:41Z",
            "created": "2017-09-27T22:32:58Z",
            "fileType": "xml",
            "parserVersion": 4,
            "hasInstructions": false,
            "directives": {
                "file_uri_as_namespace": "true"
            },
            "namespace": {
                "name": "dir11/test.xml"
            },
            "totalStringCount": 1,
            "totalWordCount": 27,
            "totalCount": 3,
            "items": [
            .......
            ]
        }
    }
}
```
File was uploaded without my directive. Directive `"file_uri_as_namespace": "true"` is added by smartling automatically.

```
$ smartling-cli files push dir11/test.xml --directive smartling.string_format_paths
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.redactedWriter.Write(0xc420050440, 0x3, 0x4, 0xc4201b8300, 0x72, 0xc0, 0x13f5a00, 0xc42003e000, 0xc42003dd88)
	/go/src/cli/redacted_log.go:54 +0x2f5
main.(*redactedWriter).Write(0xc4200e2460, 0xc4201b8300, 0x72, 0xc0, 0x16365f0, 0x0, 0x0)
	<autogenerated>:1 +0x74
fmt.Fprintln(0x15d6e80, 0xc4200e2460, 0xc42003dd88, 0x1, 0x1, 0x37, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:248 +0x8b
main.reportError(0x15d85c0, 0xc420050a80)
	/go/src/cli/main.go:240 +0xbf
main.main()
	/go/src/cli/main.go:232 +0x3ea
```
I expected `Should be in the form of <name>=<value>.`.

**Comment by seletskiy** [comment]
@dimitrystd: well, you need to omit `smartling.` from your directive name, since it's already prepended automatically. Unfortunately, Smartling API do not report any error for that case.

BTW, panic should be fixed now.

Please, test it again.

**Comment by dimitrystd** [comment]
Verified with command
```
smartling-cli files push dir11/test.xml --directive string_format_paths="html : translationObjectFile/translationObjectProperties/" -r namespace="test namespace"
```
