### ISSUE TITLE
Remove "project" from mandatory parameter of  all commands

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/smartling-cli#8]
**Actual**:
```
smartling-cli>smartling-cli.exe
Usage:
  smartling -h | --help
  smartling [options] projects list
  smartling [options] projects info <project>
  smartling [options] files list <project> [<uri>] [-s] [--format=]
  smartling [options] files pull <project> [<uri>] [-l=] [-d=]
  smartling [options] files status <project> [<uri>] [--format=]
```

**Expected**:
User always works with the single project. If user needs to switch to another project then he has options:
* Create one more config and set a path to another config
* Override project with `-p` parameter

**DoD**:
* `project` is not mandatory parameter of any command. It's always resolved from: config; parameter; env
* Replace `project` with `project id` in all user messages (to be consistent with dashboard)

**Comment by dimitrystd** [comment]
Tested the new code, looks like it's still expects `project` parameter
```
D:\Projects\Connectors\smartling-cli>smartling-cli.exe files list
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.doFilesList(0xc0423a2f60, 0xc0423a2e60, 0x1e, 0xc042350700, 0x37, 0xc0423a2f20, 0x13, 0xc0423ae3a0, 0x9, 0x4, ...)
        D:/Projects/Connectors/smartling-cli/do_files_list.go:17 +0x753
main.files(0xc0423a2e60, 0x1e, 0xc042350700, 0x37, 0xc0423a2f20, 0x13, 0xc0423ae3a0, 0x9, 0x4, 0xc0420f43b9, ...)
        D:/Projects/Connectors/smartling-cli/main.go:246 +0x3f5
main.main()
        D:/Projects/Connectors/smartling-cli/main.go:126 +0x40d
```

**Comment by seletskiy** [comment]
Try again, should be fixed now.
